# Generated by Django 6.0.4 on 2026-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('max_produtos', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'ativo'), ('deactivate', 'desativado')], default='ativo')),
            ],
        ),
    ]
