# Generated by Django 6.0.4 on 2026-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_de_produtos', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('atv', 'ativo'), ('des', 'desativo')], default='ativo')),
                ('produtos', models.ManyToManyField(to='produto.produto')),
            ],
        ),
    ]
