# Generated by Django 6.0.4 on 2026-04-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PRO', 'processados'), ('LAT', 'laticínios'), ('CAR', 'carnes'), ('BEB', 'bebidas'), ('LIM', 'produtos de limpeza'), ('PLA', 'plásticos')], default='', max_length=3)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('preco_de_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('preco_de_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True)),
                ('setor_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setor.setor')),
            ],
        ),
    ]
